version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: biblioteca
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
     - ./mysql_data:/var/lib/mysql

  node:
    image: node:20
    ports: 
     - 3000:3000
    volumes: 
     - ./source/:/app/
    environment: 
     - TZ:"America/Lima"
    tty: true

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 5000:80
    environment:
      - PMA_ARBITRARY=1